### ISSUE TITLE
Add example usage to more functions

### ISSUE THREAD

**Issue by Benjamin-Lee** [nlgranger/SeqTools#1]
Some functions have example usage in their API docs such as `seqtools.smap()` but others do not. Would it be possible to add more example usage into the API docs? A minimal example for functions such as `seqtools.split()` would be appreciated.

**Comment by nlgranger** [comment]
Please review https://github.com/nlgranger/SeqTools/commit/35ed5c1e49ccb0e4afb9ee85416badf330f646a2 and see if it provide sufficient clarity about usage. A preview of the updated documentation is available [here](https://seqtools-doc.readthedocs.io/en/joss_review/).

**Comment by Benjamin-Lee** [comment]
Great!
