### ISSUE TITLE
Add community guidelines

### ISSUE THREAD

**Issue by Benjamin-Lee** [nlgranger/SeqTools#2]
As per the JOSS review standards:

>  Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by nlgranger** [comment]
Would https://github.com/nlgranger/SeqTools/commit/ff7f2aedcc252587c2f0986cdc83bcf982542a46 add sufficient information?

**Comment by Benjamin-Lee** [comment]
I'm sorry, I seem to have missed that information in the README. ff7f2ae looks good!
