### ISSUE TITLE
Typo in docs/installation.rst

### ISSUE THREAD

**Issue by Benjamin-Lee** [nlgranger/SeqTools#3]
https://github.com/nlgranger/SeqTools/blame/master/docs/installation.rst#L14 needs to read `pip install git+https://github.com/nlgranger/SeqTools.git`.

**Comment by nlgranger** [comment]
I missed that, thank you. Fixed by https://github.com/nlgranger/SeqTools/commit/d608546b6a40ec3f6b3631b0262c229f00d32e47.
