### ISSUE TITLE
Handling SIGBUS/SIGSEGV in multiprocessing

### ISSUE THREAD

**Issue by pluiez** [nlgranger/SeqTools#4]
Hi, I'm having two questions.
1. handling signals 
SeqTools seems only dealing with SIGINT signal currently. While in real-case usage, for example, training a neural model in PyTorch or Tensorflow might come up with other signals that terminate the current main process. In this situation, the created worker processes still keep running, which is not how we expected them to.
I'm wondering how to deal with SIGBUS/SIGSEGV signals when using prefetch with multiprocessing. PyTorch's torch.utils.data.dataloader.DataLoader will shutdown the worker processes  right after the main process receives SIGINT/SIGBUS/SIGSEGV/... signals. 

2. it's not necessary to re-creates the worker processes everytime calling .prefetch
In Tensorflow, we can enable cached reading from super-large text files by setting buffer_size parameter in the `Dataset` object, so that we can load only `buffer_size` text lines into memory at a time to largely reduce memory footprint. So iterating through the whole dataset eventually ends up with many many buffers. Assuming each of the buffers is a list, which can faciliate SeqTools' useful functionalities. If I use seqtools.prefetch(buffer, nworkers=6, method='process') for each buffer one after another, the 6 workers will always be re-created everytime the `prefetch` method is invoked. However, these processes are reusable since they share the same kind of data source, and the cost of creating and destroy processes will be quite expensive.

**Comment by nlgranger** [comment]
Regarding 1. The problem solved by this code is not that children processes keep living but that they intercept the sigint signal that was meant to the parent. I cannot think of a reason to cleanly handle signals related to unrecoverable errors, so I did not bother with the other signals.
I suppose I could improve the handling of error signals raised by a child (a child generating a segfault for example).
The call to subprocess.Process does not use daemon=True, so they should not outlive the parent. Beside, there are tests and a timeout to check wether the parent has died, but if you find an issue with it, please let me know.

About 2: Can you elaborate on your use-case? prefetch is designed to be used at a high level such as the output of a preprocessing pipeline, so it is only created once to encapsulate a large sequence.

**Comment by pluiez** [comment]
@nlgranger Hi, for handling signals, here is a piece of code.
```python
import time

import seqtools

if __name__ == '__main__':
    x = list(range(10000))


    def f(i):
        time.sleep(1)
        print("In subprocess:",i)


    y = seqtools.smap(f, x)
    fetch = seqtools.prefetch(y, 1000, 2, 'process')
    time.sleep(20)
```
After the above code is run, I  manually send SIGBUS/SIGSEGV signal to the main process, but the child subprocesses continue to run till the end.

For 2, this is another example.
```python
import itertools
import random

import numpy
import seqtools


def reader(bufsize=100000):
    with open('a_20GB_text_file') as r:
        while True:
            buffer = [x.strip() for x in itertools.islice(r, bufsize)]
            yield buffer
            if len(buffer) < bufsize:
                break


if __name__ == '__main__':
    word2id = {}


    def preprocess(line):
        words = line.split()
        ids = [word2id[word] for word in words]
        return numpy.array(ids)


    for epoch in range(n):  # repeat `n` epochs
        step_in_epoch = 0
        for text_buffer in reader(100000):  # a single epoch
            random.shuffle(text_buffer)  # impose randomness
            processed = seqtools.smap(preprocess, text_buffer)

            # Run preprocessing in background.
            # However, `prefetch` returns a new `PrefetchedSeqeuence` object that wraps
            # a `AsyncSequence` object, which creates new processes every time when it's initialized.
            fetch = seqtools.prefetch(processed, 10000, 2, 'process')

            while fetch:
                batch = fetch[:batch_size]
                fetch = fetch[batch_size:]
                batch = make_batch(batch)
                # Also, when the segmentation fault or some other critical errors happened in main process,
                # such as during a model running forward and backward on GPU, the sub-processes in `prefetch` 
                # won't be notified to exit. But the torch.utils.data.dataloader can handle these signals 
                # correctly.
                loss = model(batch)
                loss.backward()
                step_in_epoch += 1

```

**Comment by nlgranger** [comment]
I think I fixed the first problem in the latest commit. Could you please try it?

**Comment by pluiez** [comment]
What do you mean by spurious background process?

**Comment by nlgranger** [comment]
I was using [multiprocessing.Manager](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.sharedctypes.multiprocessing.Manager) to transmit values and error data between workers and the main process. It uses an extra background process which can outlive its parent, and I could not find any way to clean it up. The new code uses pipes connecting the workers to the parent directly.

**Comment by nlgranger** [comment]
v1.0.0 introduces reworked prefetching. Workers are now independent (daemon) processes that periodically check wether the parent process is alive. Communication between the workers and the main script relies on queues and pipes which don't require extra background processes that need to be cleanup.
